app = 'xforce-frontend'  # Unique name (e.g., not 'xforce' if backend uses that)
primary_region = 'fra'

[build]
  builder = "paketobuildpacks/builder:base"  # 'base' is lighter than 'full', sufficient for Next.js
  buildpacks = ["gcr.io/paketo-buildpacks/nodejs"]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  NODE_ENV = "production"
  PORT = "3000"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024